type = "webpack"
workers_dev = true
compatibility_date = "2021-11-30"

name = "check-for-prizes"
kv_namespaces = [{ binding = "CHECK_FOR_PRIZES", id = "", preview_id = "" }]

account_id = "" # Production account

[triggers]
crons = ["0/2 * * * *"]

[vars]
APP_NAME = 'check-for-prizes'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
ETHERSCAN_API_KEY = ''
