type = "webpack"
workers_dev = true
compatibility_date = "2022-01-31"

name = "check-for-prizes"
kv_namespaces = [{ binding = "CHECK_FOR_PRIZES", id = "bcae9a88a9d24ab7bf6362aa84bb9a82", preview_id = "bc842d93e65a47c7a69a95ebe3769d4e" }]

zone_id = "def387de8d901fd1677399cebb5f072d"
account_id = "016652b84a09dea39b3a9c6437b88062" # Production account

[vars]
APP_NAME = 'check-for-prizes'
SENTRY_KEY = '4539f33a2b744bd78a36c38a9e0659f9'
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = '3975ec7fe56843d4a24eec105f45fcb7cf214a3a6f174227b864ea35f8f159cc'
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
