name = "contract-addresses-updater"
type = "javascript"
zone_id = ""
account_id = "" # Production account
route = ""
workers_dev = true
compatibility_date = "2022-04-26"

[[kv_namespaces]]
binding = "CONTRACT_ADDRESSES"
preview_id = "a7ac2bd9e565494d83aa01779679e816"
id = "dc56d0dcc5ab49069871db83df8df2a4"

[vars]
APP_NAME = 'contract-addresses-updater'
ENVIRONMENT_NAME = 'worker'
INFURA_ID = ''
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'cloudflare-workers'
SENTRY_AUTH_TOKEN = ''

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"

[triggers]
crons = ["0 0 * * *"]
