type = "webpack"
workers_dev = true

account_id = "" # Production account

[triggers]
crons = ["0/2 * * * *"]

[env.mainnet]
name = "mainnet-pool-updater"
kv_namespaces = [{ binding = "POOLS", id = "e01e5ae04e134d779382f36ca2ff6cda", preview_id = "94a5c29315bb4d31abba4d959c67b2d4" }]

[env.rinkeby]
name = "rinkeby-pool-updater"
kv_namespaces = [{ binding = "POOLS", id = "e01e5ae04e134d779382f36ca2ff6cda", preview_id = "94a5c29315bb4d31abba4d959c67b2d4" }]

[env.polygon]
name = "polygon-pool-updater"
kv_namespaces = [{ binding = "POOLS", id = "e01e5ae04e134d779382f36ca2ff6cda", preview_id = "94a5c29315bb4d31abba4d959c67b2d4" }]

[env.binance]
name = "binance-pool-updater"
kv_namespaces = [{ binding = "POOLS", id = "e01e5ae04e134d779382f36ca2ff6cda", preview_id = "94a5c29315bb4d31abba4d959c67b2d4" }]


[env.mainnet.vars]
CHAIN_ID = '1'
APP_NAME = 'mainnet-pool-updater'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
INFURA_ID = ''

[env.rinkeby.vars]
CHAIN_ID = '4'
APP_NAME = 'rinkeby-pool-updater'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
INFURA_ID = ''

[env.polygon.vars]
CHAIN_ID = '137'
APP_NAME = 'polygon-pool-updater'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
INFURA_ID = ''

[env.binance.vars]
CHAIN_ID = '56'
APP_NAME = 'binance-pool-updater'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
INFURA_ID = ''
