type = "webpack"
workers_dev = true

account_id = "" # Production account

[triggers]
crons = ["0/2 * * * *"]

[env.mainnet]
name = "mainnet-gas-updater"
# kv_namespaces = [{ binding = "GAS", id = "", preview_id = "" }]

[env.polygon]
name = "polygon-gas-updater"
# kv_namespaces = [{ binding = "GAS", id = "", preview_id = "" }]


[env.mainnet.vars]
CHAIN_ID = '1'
APP_NAME = 'mainnet-gas-updater'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
ETHERSCAN_API_KEY = ''

[env.polygon.vars]
CHAIN_ID = '137'
APP_NAME = 'polygon-gas-updater'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
ETHERSCAN_API_KEY = ''
