name = "web3-provider-proxy"
type = "javascript"
zone_id = ""
account_id = "" # Production account
workers_dev = true
compatibility_date = "2022-04-26"

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"

[env.ethereum-mainnet]
name = "ethereum-mainnet-web3-provider-proxy"

[env.ethereum-mainnet.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 13
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://mainnet.infura.io/v3/'
FALLBACK_PROVIDER = 'https://mainnet.infura.io/v3/'
SENTRY_DSN = ''

[env.rinkeby]
name = "rinkeby-web3-provider-proxy"

[env.rinkeby.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 15
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://rinkeby.infura.io/v3/'
FALLBACK_PROVIDER = 'https://rinkeby.infura.io/v3/'
SENTRY_DSN = ''

[env.goerli]
name = "goerli-web3-provider-proxy"

[env.goerli.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 15
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://goerli.infura.io/v3/'
FALLBACK_PROVIDER = 'https://goerli.infura.io/v3/'
SENTRY_DSN = ''

[env.optimism-mainnet]
name = "optimism-mainnet-web3-provider-proxy"

[env.optimism-mainnet.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 4
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://optimism-mainnet.infura.io/v3/'
FALLBACK_PROVIDER = 'https://optimism-mainnet.infura.io/v3/'
SENTRY_DSN = ''

[env.arbitrum-mainnet]
name = "arbitrum-mainnet-web3-provider-proxy"

[env.arbitrum-mainnet.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 4
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://arbitrum-mainnet.infura.io/v3/'
FALLBACK_PROVIDER = 'https://arbitrum-mainnet.infura.io/v3/'
SENTRY_DSN = ''

[env.arbitrum-goerli]
name = "arbitrum-goerli-web3-provider-proxy"

[env.arbitrum-goerli.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 4
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://arbitrum-goerli.infura.io/v3/'
FALLBACK_PROVIDER = 'https://arbitrum-goerli.infura.io/v3/'
SENTRY_DSN = ''

[env.optimism-kovan]
name = "optimism-kovan-web3-provider-proxy"

[env.optimism-kovan.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 15
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://optimism-kovan.infura.io/v3/'
FALLBACK_PROVIDER = 'https://optimism-kovan.infura.io/v3/'
SENTRY_DSN = ''

[env.optimism-goerli]
name = "optimism-goerli-web3-provider-proxy"

[env.optimism-goerli.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 15
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://optimism-goerli.infura.io/v3/'
FALLBACK_PROVIDER = 'https://optimism-goerli.infura.io/v3/'
SENTRY_DSN = ''

[env.polygon-mainnet]
name = "polygon-mainnet-web3-provider-proxy"

[env.polygon-mainnet.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 2
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://polygon-mainnet.infura.io/v3/'
FALLBACK_PROVIDER = 'https://polygon-mainnet.infura.io/v3/'
SENTRY_DSN = ''

[env.polygon-mumbai]
name = "polygon-mumbai-web3-provider-proxy"

[env.polygon-mumbai.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 5
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://polygon-mumbai.infura.io/v3/'
FALLBACK_PROVIDER = 'https://polygon-mumbai.infura.io/v3/'
SENTRY_DSN = ''

[env.avalanche-mainnet]
name = "avalanche-mainnet-web3-provider-proxy"

[env.avalanche-mainnet.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 2
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://avalanche-mainnet.infura.io/v3/'
FALLBACK_PROVIDER = 'https://avalanche-mainnet.infura.io/v3/'
SENTRY_DSN = ''

[env.avalanche-fuji]
name = "avalanche-fuji-web3-provider-proxy"

[env.avalanche-fuji.vars]
APP_NAME='web3-proxy'
EDGE_CACHE_TTL = 2
BROWSER_CACHE_TTL = 0
PROVIDER = 'https://api.avax-test.network/ext/bc/C/rpc'
FALLBACK_PROVIDER = 'https://api.avax-test.network/ext/bc/C/rpc'
SENTRY_DSN = ''

