type = "webpack"
workers_dev = true
compatibility_date = "2021-11-30"

name = "gas-updater"
kv_namespaces = [{ binding = "GAS", id = "", preview_id = "" }]

account_id = "" # Production account

[triggers]
crons = ["0/2 * * * *"]

[vars]
APP_NAME = 'gas-updater'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'cloudflare-workers'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
ETHERSCAN_API_KEY = ''
INFURA_ID = ''
ZAPPER_API_KEY = ''
