type = "webpack"
workers_dev = true

account_id = "" # Production account

[env.main]
name = "discord-invite"

[env.main.vars]
H_CAPTCHA_SECRET = ''
DISCORD_APPLICATION_ID = '761068094046732298'
DISCORD_APPLICATION_PUBLIC_KEY = 'c79117593abba14eecf0f2c38f0cc2abf547cfe8c1f601e9bd6826d36e836b1e'
DISCORD_APPLICATION_SECRET = ''
APP_NAME = 'discord-invite'
ENVIRONMENT_NAME = 'worker'
