type = "webpack"
name = "tsunami-prizes"
workers_dev = true
compatibility_date = "2021-09-27"
webpack_config = "webpack.config.js"
account_id = ""
kv_namespaces = [{ binding = "TSUNAMI_PRIZES", id = "", preview_id = "" }]

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"

[vars]
APP_NAME = 'tsunami-prizes'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = ''
SENTRY_PROJECT_NAME = 'tsunami-prizes'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
INFURA_ID = ''

[env.production]
route = "tsunami.pooltogether-api.com/*"
zone_id = ""

[env.production.vars]
APP_NAME = 'tsunami-prizes'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = ''
SENTRY_PROJECT_NAME = 'tsunami-prizes'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
INFURA_ID = ''
