type = "webpack"
name = "yield-source-data-localhost"
workers_dev = true

account_id = "" # Production account

kv_namespaces = [{ binding = "YIELD_SOURCE", id = "23b2296b7dd344ac9fcea058b615d0ed", preview_id = "94c52db8f62742d7b1f9fef53d520910" }]

[triggers]
crons = ["0 * * * *"]

[vars]
APP_NAME = 'yield-source-data'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'yield-source-data'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'

[env.production]
name = "yield-source-data"
kv_namespaces = [{ binding = "YIELD_SOURCE", id = "23b2296b7dd344ac9fcea058b615d0ed", preview_id = "23b2296b7dd344ac9fcea058b615d0ed" }]
workers_dev = false
zone_id = ""
route = "yield.pooltogether-api.com/*"

[env.production.vars]
APP_NAME = 'yield-source-data'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'yield-source-data'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
