type = "webpack"
workers_dev = true

account_id = "" # Production account

[triggers]
crons = ["0/2 * * * *"]

[env.mainnet]
name = "mainnet-pod-updater"
kv_namespaces = [{ binding = "POOLS", id = "e01e5ae04e134d779382f36ca2ff6cda", preview_id = "94a5c29315bb4d31abba4d959c67b2d4" }, { binding = "PODS", id = "b77bfde46fe6485081ae56f09cdd7e8b", preview_id = "114f3f50cc3c4285a92f052e56d2d2a9" }]


[env.mainnet.vars]
CHAIN_ID = '1'
APP_NAME = 'mainnet-pod-updater'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
INFURA_ID = ''
