type = "webpack"
workers_dev = true

account_id = "" # Production account

[triggers]
crons = ["0/2 * * * *"]

[env.mainnet]
name = "mainnet-contract-addresses-updater"
kv_namespaces = [{ binding = "CONTRACT_ADDRESSES", id = "dc56d0dcc5ab49069871db83df8df2a4", preview_id = "a7ac2bd9e565494d83aa01779679e816" }]


[env.mainnet.vars]
CHAIN_ID = '1'
APP_NAME = 'mainnet-contract-addresses-updater'
SENTRY_KEY = ''
SENTRY_ORG = 'pooltogether'
SENTRY_PROJECT_ID = '5832514'
SENTRY_PROJECT_NAME = 'api-staging'
SENTRY_AUTH_TOKEN = ''
SENTRY_RELEASE = ''
ENVIRONMENT_NAME = 'worker'
INFURA_ID = ''
